// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/calculator.proto

/*
Package calcpb is a generated protocol buffer package.

It is generated from these files:
	pb/calculator.proto

It has these top-level messages:
	CalculatorRequest
	CalculatorResponse
*/
package calcpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CalculatorRequest struct {
	Num1 float64 `protobuf:"fixed64,1,opt,name=num1" json:"num1,omitempty"`
	Num2 float64 `protobuf:"fixed64,2,opt,name=num2" json:"num2,omitempty"`
}

func (m *CalculatorRequest) Reset()                    { *m = CalculatorRequest{} }
func (m *CalculatorRequest) String() string            { return proto.CompactTextString(m) }
func (*CalculatorRequest) ProtoMessage()               {}
func (*CalculatorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CalculatorRequest) GetNum1() float64 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *CalculatorRequest) GetNum2() float64 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type CalculatorResponse struct {
	Result float64 `protobuf:"fixed64,1,opt,name=result" json:"result,omitempty"`
}

func (m *CalculatorResponse) Reset()                    { *m = CalculatorResponse{} }
func (m *CalculatorResponse) String() string            { return proto.CompactTextString(m) }
func (*CalculatorResponse) ProtoMessage()               {}
func (*CalculatorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CalculatorResponse) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*CalculatorRequest)(nil), "calculator_grpc.CalculatorRequest")
	proto.RegisterType((*CalculatorResponse)(nil), "calculator_grpc.CalculatorResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Calculator service

type CalculatorClient interface {
	Calc(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error)
}

type calculatorClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorClient(cc *grpc.ClientConn) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Calc(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error) {
	out := new(CalculatorResponse)
	err := grpc.Invoke(ctx, "/calculator_grpc.Calculator/Calc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Calculator service

type CalculatorServer interface {
	Calc(context.Context, *CalculatorRequest) (*CalculatorResponse, error)
}

func RegisterCalculatorServer(s *grpc.Server, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_Calc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Calc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator_grpc.Calculator/Calc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Calc(ctx, req.(*CalculatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator_grpc.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calc",
			Handler:    _Calculator_Calc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/calculator.proto",
}

func init() { proto.RegisterFile("pb/calculator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x48, 0xd2, 0x4f,
	0x4e, 0xcc, 0x49, 0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x47, 0x88, 0xc4, 0xa7, 0x17, 0x15, 0x24, 0x2b, 0x59, 0x73, 0x09, 0x3a, 0xc3, 0x85, 0x82,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x4a, 0x73, 0x0d, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x18, 0x83, 0xc0, 0x6c, 0xa8, 0x98, 0x91, 0x04, 0x13, 0x5c, 0xcc, 0x48, 0x49,
	0x87, 0x4b, 0x08, 0x59, 0x73, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x18, 0x17, 0x5b, 0x51,
	0x6a, 0x71, 0x69, 0x4e, 0x09, 0x54, 0x3f, 0x94, 0x67, 0x14, 0xcf, 0xc5, 0x85, 0x50, 0x2d, 0x14,
	0xc8, 0xc5, 0x02, 0xe2, 0x09, 0x29, 0xe9, 0xa1, 0x39, 0x49, 0x0f, 0xc3, 0x3d, 0x52, 0xca, 0x78,
	0xd5, 0x40, 0xac, 0x55, 0x62, 0x70, 0xe2, 0x88, 0x62, 0x03, 0xa9, 0x2b, 0x48, 0x4a, 0x62, 0x03,
	0xfb, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x26, 0x6d, 0xd4, 0x04, 0x01, 0x00, 0x00,
}
